/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-sep.-2023 22:11:44 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Alquileres_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Alquileres] DROP CONSTRAINT [FK_Alquileres_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Alquileres_Personal]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Alquileres] DROP CONSTRAINT [FK_Alquileres_Personal]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Compra_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Compra] DROP CONSTRAINT [FK_Compra_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Compra_Inmueble]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Compra] DROP CONSTRAINT [FK_Compra_Inmueble]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Compra_Personal]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Compra] DROP CONSTRAINT [FK_Compra_Personal]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Alquileres]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Alquileres]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Compra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Compra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inmueble]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inmueble]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Personal]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Personal]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Venta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Venta]
GO

/* Create Tables */

CREATE TABLE [Alquileres]
(
	[CodAlquiler] int NOT NULL,
	[CodCliente] int NULL,
	[CodPersonal] int NULL,
	[Precio] int NULL
)
GO

CREATE TABLE [Cliente]
(
	[Id_Cliente] int NOT NULL,
	[Nombre] varchar(50) NULL,
	[Apellido] varchar(50) NULL,
	[Celular] varchar(50) NULL,
	[CI] varchar(50) NULL,
	[Correo] varchar(50) NULL,
	[Direccion] varchar(50) NULL
)
GO

CREATE TABLE [Compra]
(
	[Codigo] int NOT NULL,
	[Cod_Cliente] int NULL,
	[Cod_Personal] int NULL,
	[Cod_Inmueble] int NULL,
	[NumeroCompra] int NULL,
	[Precio] int NULL
)
GO

CREATE TABLE [Inmueble]
(
	[Codigo] int NOT NULL,
	[Ciudad] varchar(50) NULL,
	[Tipo] varchar(50) NULL,
	[Superficie] int NULL,
	[Ubicacion] varchar(50) NULL,
	[Estado] varchar(50) NULL,
	[Precio_referencia] int NULL
)
GO

CREATE TABLE [Personal]
(
	[CodPersonal] int NOT NULL,
	[Nombres] varchar(50) NULL,
	[Apellido] varchar(50) NULL,
	[Cargo] varchar(50) NULL,
	[Celular] varchar(50) NULL
)
GO

CREATE TABLE [Venta]
(
	[CodigoVenta] int NOT NULL,
	[Inmueble] int NULL,
	[TipoDePago] varchar(50) NULL,
	[PrecioVenta] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Alquileres] 
 ADD CONSTRAINT [PK_Alquileres]
	PRIMARY KEY CLUSTERED ([CodAlquiler] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Alquileres_Cliente] 
 ON [Alquileres] ([CodCliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Alquileres_Personal] 
 ON [Alquileres] ([CodPersonal] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([Id_Cliente] ASC)
GO

ALTER TABLE [Compra] 
 ADD CONSTRAINT [PK_Compra]
	PRIMARY KEY CLUSTERED ([Codigo] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Compra_Cliente] 
 ON [Compra] ([Cod_Cliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Compra_Inmueble] 
 ON [Compra] ([Cod_Inmueble] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Compra_Personal] 
 ON [Compra] ([Cod_Personal] ASC)
GO

ALTER TABLE [Inmueble] 
 ADD CONSTRAINT [PK_Inmueble]
	PRIMARY KEY CLUSTERED ([Codigo] ASC)
GO

ALTER TABLE [Personal] 
 ADD CONSTRAINT [PK_Personal]
	PRIMARY KEY CLUSTERED ([CodPersonal] ASC)
GO

ALTER TABLE [Venta] 
 ADD CONSTRAINT [PK_Venta]
	PRIMARY KEY CLUSTERED ([CodigoVenta] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Alquileres] ADD CONSTRAINT [FK_Alquileres_Cliente]
	FOREIGN KEY ([CodCliente]) REFERENCES [Cliente] ([Id_Cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Alquileres] ADD CONSTRAINT [FK_Alquileres_Personal]
	FOREIGN KEY ([CodPersonal]) REFERENCES [Personal] ([CodPersonal]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Compra] ADD CONSTRAINT [FK_Compra_Cliente]
	FOREIGN KEY ([Cod_Cliente]) REFERENCES [Cliente] ([Id_Cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Compra] ADD CONSTRAINT [FK_Compra_Inmueble]
	FOREIGN KEY ([Cod_Inmueble]) REFERENCES [Inmueble] ([Codigo]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Compra] ADD CONSTRAINT [FK_Compra_Personal]
	FOREIGN KEY ([Cod_Personal]) REFERENCES [Personal] ([CodPersonal]) ON DELETE No Action ON UPDATE No Action
GO
